### ISSUE TITLE
How to calculate ODS and OIS？

### ISSUE THREAD

**Issue by zhangyongzhuang** [xavysp/LDC#11]
How to calculate ODS and OIS？ I don't find the code to calculate ODS and OIS, could you tell me where the code is?

**Comment by xavysp** [comment]
Hi, sorry, I share the procedure as soon as possible but if you don't have time, please use the one used in [DexiNed issues](https://github.com/xavysp/DexiNed)
Sorry these days I am a little busy.

**Comment by zhangyongzhuang** [comment]
> Hi, sorry, I share the procedure as soon as possible

Never mind, thank you for your answer。
