### ISSUE TITLE
What is the license for this repository?

### ISSUE THREAD

**Issue by Kazuhito00** [xavysp/LDC#12]
Thank you very much for your wonderful work!

What is the license for this repository?
Apache2.0? MIT? GPLv3?

**Comment by Kazuhito00** [comment]
I am creating a demo that converts LDC to ONNX and runs it.
I plan to apply the same license as the answer to this issue.

https://github.com/Kazuhito00/LDC-ONNX-Sample

**Comment by xavysp** [comment]
Hi, thanks for using LDC:

LDC is in: https://creativecommons.org/licenses/by-nc-nd/4.0/

However, we sent a rectification to the journal,  changing the license to: https://creativecommons.org/licenses/by-nc/4.0/

But they did not help us. In our part the license is https://creativecommons.org/licenses/by-nc/4.0.

In summary, you are free to use it, and thank you for making LDC more visible.

Regards,

Xavier

**Comment by Kazuhito00** [comment]
Hi, xavysp.
Thank you for your reply.
