### ISSUE TITLE
Which weight file to use ?

### ISSUE THREAD

**Issue by yogendra-yatnalkar** [xavysp/LDC#5]
Hi,

There are 3 files weight files listed in the repo: 
- 16_model.pth
- 11_model.pth
- 5_model.pth

I have 2 questions:
- Which weight  file should I use should I use ?
- Which model class should I use ? (B4, B5, B6...etc)

Thanks in advance.

**Comment by xavysp** [comment]
Hi, thanks for interesting o LDC, a question did you read the paper?

**Comment by yogendra-yatnalkar** [comment]
Sorry for being late ..... Yes, I read the paper partially. I have understood that I have to use 16_model.pth by default and it will call the modelB4. I think I will try out with this setting. 

**Thanks a lot for the awesome work.** 

Let me know if you have any suggestion, else I will close the issue in 1 day.

**Comment by yogendra-yatnalkar** [comment]
Hi @kadirnar, sorry but for the current task, I am not calculating those scores. Apart from that, in the past when i was reading about these metrics, the following link had helped me, so forwarding those:

- https://github.com/Walstruzz/edge_eval_python
- https://answers.opencv.org/question/196702/optimal-dataset-scale-optimal-image-scale-metric/
