### ISSUE TITLE
Can't parse 'dsize'. Sequence item with index 0 has a wrong type 

### ISSUE THREAD

**Issue by sd1-1** [xavysp/LDC#9]
Same issue exists on this repo when trying to train, the fix should also be added
https://github.com/xavysp/DexiNed/issues/120
https://github.com/xavysp/DexiNed/commit/9e3cc60af1c89f256ac728fb7e981734432bf97f

**Comment by xavysp** [comment]
Hi, with respect to #120 the error was with the data (it was missing).
Let me check the other one.
